### PR TITLE
add PHP 7.0 to .travis.yml

### PR DESCRIPTION
**Pull request by sasezaki**

### CODE REVIEW

**Comment by bakura10** [comment]
Thanks!

**Comment by bakura10** [comment]
Oops I cannot merge on the phone because of the failing status. I'll do that when I come back from my holiday ;)

**Comment by macnibblet** [comment]
@bakura10 What, you are on vacation, that is not allowed :angry:

**Comment by bakura10** [comment]
still no zf3 repo => I'm bored => hello holidays ;).

**Pull request merged**
